<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Catalog.Command\Catalog.Application.Command.csproj" />
    <ProjectReference Include="..\Catalog.Contract\Catalog.Application.Contract.csproj" />
    <ProjectReference Include="..\Catalog.Query\Catalog.Application.Query.csproj" />
  </ItemGroup>

</Project>
