syntax = "proto3";

option csharp_namespace = "CatalogWebApi.Grpc.Inventory";

package inventory;

service InventoryService {
    rpc CheckStock(CheckStockRequest) returns (CheckStockResponse);
    rpc ReserveStock(ReserveStockRequest) returns (ReserveStockResponse);
}

message CheckStockRequest {
    string productId = 1;
    int32 quantity = 2;
}

message CheckStockResponse {
    bool available = 1;
}

message ReserveStockRequest {
  string productId = 1;
  int32 quantity = 2;
}

message ReserveStockResponse {
  bool success = 1;
}